# .github/workflows/release.yml

name: Build & Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  # --- Job 1: 构建桌面应用 (保持不变) ---
  build-desktop:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './src-tauri -> target'

      - name: Install frontend dependencies
        run: yarn install

      - name: Build Tauri app
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: app-v__VERSION__
          releaseName: 'App v__VERSION__'
          releaseBody: 'See the assets to download this version.'
          releaseDraft: true
          prerelease: false

  # --- Job 2: 新增的构建安卓应用的任务 ---
  build-android:
    # 确保这个job在桌面job之后运行，以利用已创建的release draft
    needs: build-desktop
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        # 定义需要构建的安卓目标架构
        # aarch64-linux-android 对应 arm64-v8a
        # x86_64-linux-android 对应 x86_64
        target: [aarch64-linux-android, x86_64-linux-android]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './src-tauri -> target'

      # 安装安卓构建所需的依赖
      - name: Install Android dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential clang libssl-dev

      # 安装对应的Rust目标
      - name: Install Rust target
        run: rustup target add ${{ matrix.target }}

      - name: Install frontend dependencies
        run: yarn install

      # 使用tauri-action构建安卓应用
      - name: Build Tauri Android app
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # 关键：指定tauri build的命令和目标
          tauriScript: yarn tauri android build --target ${{ matrix.target }}
          # 关键：与桌面job使用相同的tag，将APK上传到同一个Release
          tagName: app-v__VERSION__
          releaseName: 'App v__VERSION__'